# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField()),
                ('order_pages', models.IntegerField()),
                ('paper_subject', models.CharField(choices=[('Accounting', 'Accounting'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry')], max_length=50)),
                ('paper_topic', models.CharField(max_length=150)),
                ('paper_style', models.CharField(choices=[('APA', 'APA'), ('MLA', 'APA'), ('Harvard', 'Harvard'), ('Chicago', 'Chicago'), ('Turabian', 'Turabian'), ('Oxford', 'Oxford'), ('AMA', 'AMA'), ('Bluebook', 'Bluebook'), ('Others', 'Others')], max_length=15)),
                ('sources_num', models.IntegerField()),
                ('paper_deadline', models.CharField(max_length=150)),
                ('paper_cost', models.IntegerField()),
                ('paper_instruc', models.TextField(max_length=1200)),
                ('paper_files', models.FileField(upload_to=b'')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
