# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderjob',
            name='paper_cost',
        ),
        migrations.AlterField(
            model_name='orderjob',
            name='paper_deadline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderjob',
            name='paper_files',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
