# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regsignup', '0002_usercreationform_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('password_confirm', models.CharField(max_length=100)),
                ('signup_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('terms_agree', models.BooleanField(max_length=15)),
            ],
        ),
    ]
